### ISSUE TITLE
Game board's development

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#1]
Develop the game board that should have:
- [x] Main board
- [x] Match cards
- [x] Match cards check
- [x] Rules

Including game license and relevant links (global sprint, promo website, mozilla)

**Comment by Carotejada** [comment]
Hey @barrosgeraldo just checked out the game board. Looks cool! I think I can help with instructions but need to understand a little bit better the dynamic. Let's Vidyo soon.

**Comment by barrosgg** [comment]
is ready for now, receiving feedbacks.

**Comment by barrosgg** [comment]
Hi @cynthiapereira, the rules are ready, does this seem understandable?

[Board game](https://github.com/barrosgeraldo/mozsprint-privacy-security-situations/blob/master/game-board/Privacy%20and%20Security%20Situations%20Challenge%20-%20Board.pdf)

**Comment by barrosgg** [comment]
feedback soon from clubs captains in the learning forum.
