### ISSUE TITLE
GAME LOCALIZATION

### ISSUE THREAD

**Issue by Carotejada** [itidigitalbr/privacy-board-game#17]

**Comment by Carotejada** [comment]
[Privacy and Security Situations Challenge - SPANISH.pdf](https://github.com/barrosgeraldo/mozsprint-privacy-security-situations/files/1066873/Privacy.and.Security.Situations.Challenge.-.SPANISH.pdf)

**Comment by barrosgg** [comment]
Hi @Carotejada,

Thank you, has been added to repository and README.MD.

I'll looking for a alternative font that seems with our that support all special words.
