### ISSUE TITLE
Clean up css

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#19]

**Comment by barrosgg** [comment]
https://github.com/itidigitalbr/privacy-board-game/tree/master/website

**Comment by divayprakash** [comment]
@barrosgeraldo What exactly are you looking for here?

**Comment by barrosgg** [comment]
Hi @cynthiapereira, please, could you provide more technical information on this?

**Comment by cpswsg** [comment]
CSS contains some unused properties that should be removed to increase the performance.

**Comment by divayprakash** [comment]
Working on it!

**Comment by barrosgg** [comment]
Fixed.
