### ISSUE TITLE
Lesson plan for facilitators

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#2]
We need to create a lesson plan to **empower facilitators** to lead the game in a team, local group or general clubs.

**Comment by Carotejada** [comment]
Hey @barrosgeraldo just checked out the game board. Looks cool! I think I can help with instructions but need to understand a little bit better the dynamic. Let's Vidyo soon.

**Comment by barrosgg** [comment]
I'm sprinting in this game until the end of the night here in Brazil, I think we'll have the full board today, including the rules – that are important to understand the game. 👍

**Comment by barrosgg** [comment]
@Carotejada, rules and tips is ready! I'd like to hear from you whether it seems clear or confusing.

The rules is on the [game board](https://github.com/barrosgeraldo/mozsprint-privacy-security-situations/blob/master/game-board/Privacy%20and%20Security%20Situations%20Challenge%20-%20Board.pdf).

Thank you for your help. :D

**Comment by barrosgg** [comment]
Hi Caro, I'll work on this for now, the game is ready.

**Comment by Carotejada** [comment]
Just cheked it, it looks pretty clear to me. Love the game <3

**Comment by jvallera** [comment]
Maybe a few clubs to user test it and get back to you with feedback :) I feel like the best way to figure out what to fix is to play it.

**Comment by Carotejada** [comment]
@barrosgeraldo would love to have original file to localize it :)

**Comment by barrosgg** [comment]
Hi @jvallera and @Carotejada,
Great Julia! I'll finish the lesson plan for facilitators in the next week and test at my club and invite others clubbers on our forum to join us in this test, thank you for the suggestion.

Caro, In a few seconds I'll export to other formats, doing pull in a few minutes.

**Comment by barrosgg** [comment]
@Carotejada done.

@jvallera, tips for facilitadors is in README file, I'll open a topic on our forum to invite captains to test it.

Thank you!!! Maybe the force be with you! ⭐️ 

Closing this one.
