### ISSUE TITLE
Clean up javascript

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#20]

**Comment by barrosgg** [comment]
https://github.com/itidigitalbr/privacy-board-game/tree/master/website

**Comment by paul-baranowski** [comment]
Hey, this looks interesting. What exactly do you need done?

**Comment by barrosgg** [comment]
Hi @cynthiapereira, please, could you provide more technical information on this?

**Comment by cpswsg** [comment]
JS contains some unused properties that should be removed to increase the performance.

**Comment by paul-baranowski** [comment]
@cynthiapereira cool, i’ll take a stab at it.
