### ISSUE TITLE
Add a new suggestion to others projects: Back-to-School Privacy & Security Kit

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#22]
At last session of our website we've suggestions to others projects and games that's share same mission, let's suggest the [Back-to-School Privacy & Security Kit](https://www.mozillapulse.org/entry/427) since this is a online game based on our game.

**Comment by barrosgg** [comment]
Website folder: https://github.com/itidigitalbr/privacy-board-game/tree/master/website

**Comment by ghosh** [comment]
✋ I can pick this up. You want to add **Back-to-School Privacy & Security Kit** along with the **Cipher Fun Wheel** and **Privacy Arcade Offline Games**?

**Comment by barrosgg** [comment]
Hi @ghosh, It's cool keep with these both and add the new one, but isn't a problem replace the **Privacy Arcade Offline Games**.

**Comment by ghosh** [comment]
OK, thanks for the clarification. I'll work on it this weekend.
