### ISSUE TITLE
Update name and logo

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#23]
We've a short name for now! It's just **Privacy Board Game**, let's update all website name and logo.

*Logo will be released soon.

_Blocked issue._

**Comment by barrosgg** [comment]
Logos: https://github.com/itidigitalbr/privacy-board-game/tree/master/marketing/logo

**Comment by barrosgg** [comment]
Website repository: https://github.com/itidigitalbr/privacy-board-game/tree/master/website

**Comment by melaniegershman** [comment]
@barrosgeraldo I can work on this 👍

**Comment by barrosgg** [comment]
Done. Closing now.
