### ISSUE TITLE
Change fonts from Spanish version to the sames fonts as at Portuguese version

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#28]
Change fonts from [Spanish version](https://github.com/itidigitalbr/privacy-board-game/blob/master/board/privacy_board_game_spanish.pdf) to the sames fonts as at [Portuguese version](https://github.com/itidigitalbr/privacy-board-game/blob/master/board/privacy_board_game_portuguese.pdf).

**Comment by corroded** [comment]
Both links are 404s for me @barrosgeraldo

**Comment by barrosgg** [comment]
Hi @corroded, has been updated, thanks for report this.

**Comment by barrosgg** [comment]
I'll work on it now.

**Comment by barrosgg** [comment]
- [x] Change fonts from Spanish version to the sames fonts as at Portuguese version
- [x] Make printable A4 pages

**Comment by barrosgg** [comment]
fixed
