### ISSUE TITLE
Promo website's development

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#3]
We need to create a promotional website to publicize the game and ensure that educators/facilitators and people who love technology know more about the game and explore it.

**Comment by cpswsg** [comment]
First pull request sent #6 

Still needed:
- [x] add gitignore file
- [x] add editorconfig file
- [x] add images of board game
- [x] add links to resources
- [ ] clean up css
- [ ] clean up javascript

**Comment by cpswsg** [comment]
Pull request #10

**Comment by Carotejada** [comment]
Hola @barrosgeraldo this is awesome. Great work. Working on localization.

**Comment by barrosgg** [comment]
@Carotejada, great!!! Let us know when you are ready to add in our repository and add a translation into our official website (https://privacyandsecuritychallenge.com). However, feel free to add a Colombian version of this game by changing to common personal names and similar situations. Gracias!

**Comment by barrosgg** [comment]
Hey @cynthiapereira, thank you for your efforts here.
Before to move this forward, let's separate all changes in individual issues. :)
