### ISSUE TITLE
Make the supporters session responsive

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#53]
As you can see the **"Supporters"** session at the [website page](https://itidigitalbr.github.io/privacy-board-game/website/) [works fine for desktop](https://screenshots.firefox.com/2n5sSCl2HO1iYrZb/itidigitalbr.github.io), but for [mobile devices isn't works fine](https://user-images.githubusercontent.com/14970832/31698914-b0848fa0-b39e-11e7-9347-9524244104f6.png), to make this reponsive now, the tasks are:

- [x] [Remove the png that's have all logos in a unique image](https://itidigitalbr.github.io/privacy-board-game/website/images/supporters.png).

- [x] Add all [logos images](https://github.com/itidigitalbr/privacy-board-game/tree/master/website/images/supporters-logos) individually in the **"Supporters"** session horizontally, and vertically should appear just for mobile devices.

If you need help, please comment here and I'll reply in some minutes/hours.

**Comment by jayporta** [comment]
I'd like to take this. I've been using GitHub for a while but never contributed to anything. I've done fixes like this for my previous employer all the time. 

Edit: I just checked the link it seems to have been done already.

**Comment by barrosgg** [comment]
@jayporta, you can help us yet, could you check if in mobile devices is working fine? I think that's need fix somethings to make it responsive. See:
![deepinscreenshot_select-area_20171018103334](https://user-images.githubusercontent.com/14970832/31718774-d5e7420a-b3ef-11e7-8f0f-23addafdb9f4.png)

**Comment by jayporta** [comment]
I see what you  mean. It looks fine on my phone (Android, Chrome) but not on the mobile browser emulator in Chrome. I don't own an iPhone or Apple computer so I can't test there. Also, the animated text thing is causing everything around it to jump around. I can fix that too if you'd like.

**Comment by barrosgg** [comment]
Yes, I would like you fix it. Thanks. :)

**Comment by jayporta** [comment]
OK. Like I said this is my first contribution, so do I create a pull request for each fix or just apply fixes and submit for review?

**Comment by barrosgg** [comment]
Just apply fixes and submit for review. ;)

**Comment by jayporta** [comment]
Done. So do I just commit to master?

**Comment by barrosgg** [comment]
Yes.

**Comment by jayporta** [comment]
Committed. Thanks for giving me a shot.

**Comment by barrosgg** [comment]
Hi @jayporta, when is ready please make a pull request, thanks for the help.

**Comment by jayporta** [comment]
Oh it's been done since I sent that message. Sorry I'm new to this. I'll do it when I get home.

**Comment by jayporta** [comment]
Let me know whether or not I've done the pull request properly. If not, I'll fix it ASAP.

**Comment by barrosgg** [comment]
@jayporta, as you can see [here](https://github.com/itidigitalbr/privacy-board-game/pulls), we don't received a pull request from you. Please, fork this repository and [see the instructions to send a pull request to this repository](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). Thanks.

**Comment by barrosgg** [comment]
fixed.
