### ISSUE TITLE
Remove black borders from the text

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#55]
We do not consider using the black borders in the text to highlight the titles and paragraphs. The task is:

- [ ] Remove black borders from all text

**Comment by abderra7** [comment]
I'm interested on that

**Comment by rudr4x5h** [comment]
@barrosgeraldo this is a cool project! 
I just wanted to ask which web project you're referring to in this issue? The one present in `privacy-board-game/website/` directory? because I can't seem to find any black borders there.

**Comment by barrosgg** [comment]
@d3vil0p3r, yes, the website code is inside the website folder, that's alive at https://itidigitalbr.github.io/privacy-board-game/website/.
 The black borders is the `text-shadow` inside the CSS.
![deepinscreenshot_select-area_20171018192240](https://user-images.githubusercontent.com/14970832/31743406-d0c64952-b439-11e7-9ade-5dbdb4b09f88.png)

**Comment by sinhuemx** [comment]
Look nice! i can help you my friend

**Comment by rudr4x5h** [comment]
@barrosgeraldo thanks for explanation. Working on it! 👍

**Comment by MaulikSS** [comment]
I'd like to help with this issue
