### ISSUE TITLE
Add new button for "Contribute Now - It's on GitHub"

### ISSUE THREAD

**Issue by barrosgg** [itidigitalbr/privacy-board-game#57]
Our project is open to contributors, we need to add a button next to the "Play Now - It's open" button that will have the text "Contribute Now - It's on GitHub" and the [link will be this one](https://github.com/itidigitalbr/privacy-board-game).

- [x] Add a new button next the "Play Now..." button: "Contribute Now - It's on GitHub" and the [link should be this one](https://github.com/itidigitalbr/privacy-board-game).

**Comment by invacuo** [comment]
Is there a specific design for this button? Or should it look just like the "Play Now..." button?

**Comment by barrosgg** [comment]
Hi @invacuo, thanks for the question, this button should look just like the "Play Now" button. But if you've another suggestion feel free to submit via pull request.

**Comment by invacuo** [comment]
@barrosgeraldo Looks like there are two PRs opened for this one. Here is mine https://github.com/itidigitalbr/privacy-board-game/pull/60

**Comment by jgalianoz** [comment]
@barrosgeraldo If there seem to be two open PR. #58 

Add **target = "_ blank"** so your page does not lose users.

**Comment by barrosgg** [comment]
fixed, thanks :)
